#!/usr/bin/env bash
# Install haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web servers

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 17272-web-01 54.158.218.254 check
   server 17272-web-02 52.91.184.53 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
