#!/usr/bin/env bash
# bash script to echo minutes and hours
i=0
while [ $i -le 12 ]; do
       echo "Hour: $i"
       j=1
       while [ $j -le 60 ]; do
	       echo $j
	       ((j++))
       done
       ((i++))
done
